FROM ubuntu:22.04

RUN apt update \
    && apt install -y \
    python3.10\
    python3-pip \
    curl \
    sudo

COPY requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN apt-get autoremove -y && apt-get clean && \
    rm -rf /usr/local/src/*